import axios from "axios"


// Generated by https://quicktype.io

export interface AppointmentInterface {
    id:                    string;
    appointment_date:      Date;
    appointment_status:    'pending' | 'confirmed' | 'cancelled';
    address_snapshot:      string;
    email_snapshot:        string;
    phone_number_snapshot: string;
    comment:               string;
    doctor_id:             string;
    patient_id:            string;
    created_at:            Date;
    updated_at:            null;
    deleted_at:            null;
    patient:               Patient;
}

export interface Patient {
    name: string;
    rut:  string;
}




export const getAppointments = async (token: string, doctor_id: string): Promise<AppointmentInterface[]> => {
    try {
        const url = `https://nautilus-api-test.up.railway.app/appointments?doctorID=${doctor_id}`
        const response = await axios.get(url, {
            headers: {
                Authorization: `Bearer ${token}`
            }
        })
        return response.data;
    } catch (err) {
        console.log(err)
        throw err
    }
}