// Generated by https://quicktype.io

export interface Doctor {
    id:                string;
    name:              string;
    phone_number:      string;
    rut:               string;
    specialization_id: string;
    user_id:           string;
    created_at:        Date;
    updated_at:        null;
    deleted_at:        null;
}
